name: Kriteria 3 - MLProject CI & Docker Build

on:
  push:
    branches: [ main ] # Memicu saat ada push ke branch main

jobs:
  run-mlproject-and-build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install MLflow
        run: |
          # Kita hanya perlu mlflow di runner utama
          pip install mlflow==2.19.0

      # --- TAHAP SKILLED: Menjalankan MLProject ---
      - name: Jalankan MLflow Project (Re-training)
        # Kredensial ini diperlukan agar mlflow run bisa log ke DagsHub
        env: 
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_TRACKING_URI }}
        run: |
          eval "$(conda shell.bash hook)"
          # Menjalankan project dan memberi nama eksperimen
          mlflow run . --experiment-name "CI - Automated Training"

      # --- TAHAP ADVANCED: Build & Push Docker ---
      - name: Build Docker Image via MLflow
        id: build_docker
        # Kredensial ini diperlukan agar 'mlflow models build-docker' 
        # bisa mengunduh model dari DagsHub
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_TRACKING_URI }}
        run: |
          # Baca Run ID yang disimpan oleh skrip modelling.py
          RUN_ID=$(cat run_id.txt)
          echo "Membangun image untuk Run ID: $RUN_ID"
          
          # GANTI DENGAN NAMA DOCKER HUB ANDA: <username>/<image-name>
          IMAGE_NAME="farchandio/smsml-stroke-model:latest"

          # PERBAIKAN: Perintah yang benar adalah 'mlflow models build-docker'
          mlflow models build-docker \
            -m "runs:/${RUN_ID}/model" \
            -n $IMAGE_NAME \
            --enable-mlserver
          
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOKCERHUB_TOKEN }} # Pastikan nama secret Anda benar

      - name: Push Docker image ke Docker Hub
        run: docker push ${{ steps.build_docker.outputs.image_name }}
