name: Kriteria 3 - MLProject CI & Docker Build

on:
  push:
    branches: [ main ] # Memicu saat ada push ke branch main

jobs:
  run-mlproject-and-build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install MLflow dan DagsHub
        run: |
          pip install mlflow==2.19.0 dagshub

      # --- Konfigurasi Kredensial (dari Secrets) ---

      # --- TAHAP SKILLED: Menjalankan MLProject ---
      - name: Jalankan MLflow Project (Re-training)
        env: 
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      # ... (secrets lainnya)
        run: |
          eval "$(conda shell.bash hook)"
          mlflow run . --experiment-name "CI - Automated Training"

      # --- TAHAP ADVANCED: Build & Push Docker ---
      - name: Build Docker Image via MLflow
        id: build_docker
        run: |
          # Baca Run ID yang disimpan oleh skrip modelling.py
          RUN_ID=$(cat run_id.txt)
          echo "Membangun image untuk Run ID: $RUN_ID"
          
          # GANTI DENGAN NAMA DOCKER HUB ANDA: <username>/<image-name>
          IMAGE_NAME="farchandio/smsml-stroke-model:latest"

          # 'mlflow build-docker' akan mengambil model dari DagsHub
          # karena MLFLOW_TRACKING_URI sudah diatur
          mlflow build-docker \
            -m "runs:/${RUN_ID}/model" \
            -n $IMAGE_NAME \
            --enable-mlserver
          
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Login ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image ke Docker Hub
        run: docker push ${{ steps.build_docker.outputs.image_name }}
